apiVersion: batch/v1
kind: Job
metadata:
  name: ectmb-train
spec:
  template:
    spec:
      containers:
      - name: ectmb
        image: humansimon/ectmb-nodeps
        command: ["calcTMBNoMount", "train"]
      restartPolicy: Never
